name: erad2026-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - jupyterlab
  - jupyter_server
  - notebook
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - jupyterlab-myst
  - mystmd
  - jupytext
  - jupyterlab_rise
  - jupyter-lsp
  - python-lsp-server
  - jupyterlab-git
  - sphinx-pythia-theme
  - arm_pyart
  - cartopy
  - icechunk
  - matplotlib
  - numpy
  - wradlib>=2.9.5
  - xhistogram
  # - pydda
  - zarr
  - xarray
  - xradar>=0.12.0
  - numpy
  # this is needed for gpm-api
  - gpm-api>=0.3.1
  - pycolorbar>=0.1.0
  - ximage>=0.0.5
  - shapely>=2.0.0
  - geopandas
  - geoviews
  - xoak
  - scikit-learn
  - folium
  # needed for s3 and filesystem
  - fsspec
  - s3fs
  # needed for tabular (parquet) data access
  - pyarrow
  - openpyxl
  # this is needed for baltrad compilation
  - compilers
  - make
  - gnuconfig
  - bash
  - libaec
  - coreutils
  - autoconf
  - automake
  - expat
  - tar
  - libblas=*=*netlib
  - liblapacke=*=*netlib
  # this is needed for notebooks
  - zip
  # debugging
  - sphinx>=7.4.7
  - sqlite>=3.46.0
  - pytest
  - pytest-xdist
  # this is needed for PyDDA performance
  # - jaxopt
  # - tensorflow>=2.6
  # - tensorflow-probability>=0.24
  # interactive plotting
  - hvplot
  - datashader
  # needed for wradlib
  - bottleneck
  - rioxarray
  # needed for LROSE / pyrad
  - metpy
  - pip

